// Importing necessary modules. Note that direct font imports like this might not be standard in a pure JSX setup.
import "./globals.css";

// Assuming the Inter font is somehow applied or imported differently as the original import method is specific to TypeScript.
// You might need to handle font importing directly in your CSS or through a <link> in your HTML/JSX.

// Removed the type declaration for metadata.
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Simplified component props to use React's built-in types, removing TypeScript specific Readonly utility type.
export default function RootLayout({ children }) {
  // Assuming `inter.className` is handled differently or omitted due to the original TypeScript-specific font loading approach.
  // The className application based on `inter` might need adjustment.
  return (
    <html lang="en">
      <body>{children}</body> {/* Removed the className application */}
    </html>
  );
}
